GET http://localhost:3000/
###

GET http://localhost:3000/todos/9
###

GET http://localhost:3000/agenda?date=2021--04
###

POST http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 9,
  "todo": "Finali event theme",
  "priority": "LOW",
  "status": "TO DO",
  "category": "HOME",
  "dueDate": "2021-02-22"
}
###

PUT http://localhost:3000/todos/6/
Content-Type: application/json

{
"todo": "Finalizeevent theme"
}
###

DELETE http://localhost:3000/todos/6/
###